language: node_js
dist: trusty
sudo: required
node_js:
  - '8'
services:
  - redis-server
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget https://archive.apache.org/dist/cassandra/2.2.5/apache-cassandra-2.2.5-bin.tar.gz
    && tar -xzf apache-cassandra-2.2.5-bin.tar.gz && sudo sh apache-cassandra-2.2.5/bin/cassandra
script: SEGUIR_DEBUG=true npm run test
deploy:
  provider: npm
  email: clifton.cunningham@tes.co.uk
  api_key: $NPM_TOKEN
  on:
    tags: true
